export function assertUnreachable(e){throw new Error(`Unexpected object: ${e}`)}